# Shell variables
# Generated by 'wal'
wallpaper='/home/ayoub/Pictures/wallpapers/pixelcity.png'

# Special
background='#0C0D18'
foreground='#d0d4d7'
cursor='#d0d4d7'

# Colors
color0='#0C0D18'
color1='#555D69'
color2='#AE8C68'
color3='#6B7785'
color4='#7994B0'
color5='#7FA0C1'
color6='#84A5C6'
color7='#d0d4d7'
color8='#919496'
color9='#555D69'
color10='#AE8C68'
color11='#6B7785'
color12='#7994B0'
color13='#7FA0C1'
color14='#84A5C6'
color15='#d0d4d7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
