--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/ayoub/Pictures/wallpapers/pixelcity.png"

-- Special
background="#0C0D18"
foreground="#d0d4d7"
cursor="#d0d4d7"

-- Colors
color0="#0C0D18"
color1="#555D69"
color2="#AE8C68"
color3="#6B7785"
color4="#7994B0"
color5="#7FA0C1"
color6="#84A5C6"
color7="#d0d4d7"
color8="#919496"
color9="#555D69"
color10="#AE8C68"
color11="#6B7785"
color12="#7994B0"
color13="#7FA0C1"
color14="#84A5C6"
color15="#d0d4d7"
