--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/ayoub/Pictures/wallpapers/ign_groot.png"

-- Special
background="#1a1e25"
foreground="#ccbdcd"
cursor="#ccbdcd"

-- Colors
color0="#1a1e25"
color1="#577092"
color2="#5F7AA0"
color3="#917690"
color4="#7587AE"
color5="#6B94AF"
color6="#7AACC5"
color7="#ccbdcd"
color8="#8e848f"
color9="#577092"
color10="#5F7AA0"
color11="#917690"
color12="#7587AE"
color13="#6B94AF"
color14="#7AACC5"
color15="#ccbdcd"
