# Shell variables
# Generated by 'wal'
wallpaper='/home/ayoub/Pictures/wallpapers/ign_unsplash44.png'

# Special
background='#1b1e25'
foreground='#afb8c3'
cursor='#afb8c3'

# Colors
color0='#1b1e25'
color1='#4B5063'
color2='#4B566B'
color3='#566277'
color4='#606B7E'
color5='#5C6882'
color6='#636F86'
color7='#afb8c3'
color8='#7a8088'
color9='#4B5063'
color10='#4B566B'
color11='#566277'
color12='#606B7E'
color13='#5C6882'
color14='#636F86'
color15='#afb8c3'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
