--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/ayoub/Pictures/wallpapers/ign_venom.jpg"

-- Special
background="#11161e"
foreground="#dfe1e6"
cursor="#dfe1e6"

-- Colors
color0="#11161e"
color1="#686970"
color2="#707888"
color3="#848582"
color4="#9FAB98"
color5="#ABC392"
color6="#B7BDC9"
color7="#dfe1e6"
color8="#9c9da1"
color9="#686970"
color10="#707888"
color11="#848582"
color12="#9FAB98"
color13="#ABC392"
color14="#B7BDC9"
color15="#dfe1e6"
