# Shell variables
# Generated by 'wal'
wallpaper='/home/ayoub/Pictures/wallpapers/ign_groot.png'

# Special
background='#1a1e25'
foreground='#ccbdcd'
cursor='#ccbdcd'

# Colors
color0='#1a1e25'
color1='#577092'
color2='#5F7AA0'
color3='#917690'
color4='#7587AE'
color5='#6B94AF'
color6='#7AACC5'
color7='#ccbdcd'
color8='#8e848f'
color9='#577092'
color10='#5F7AA0'
color11='#917690'
color12='#7587AE'
color13='#6B94AF'
color14='#7AACC5'
color15='#ccbdcd'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
